"""
Verification Script for the physical_law Paper (Dissipative Projection)
====================================================================
Each section corresponds to a Theorem or incidental exploration noted in
the paper. Sections are written to be runnable independently, with each
function containing whatever imports/definitions it needs.

Contents:
  - T1  (Section 4.1): time integral of the dissipative semigroup vs Delta^-1
  - T2  (Section 4.2): time integral of the d-dimensional heat kernel
  - Sec.6 addendum: energy-neutrality of the triple-coupling tensor
                     generated by the advection term (u . grad)u.
                     NOTE: this last piece is an INCIDENTAL exploration
                     using standard energy methods (Fourier/Parseval),
                     not a result derived from the Delta structure itself.
                     It is not connected to the Navier-Stokes Millennium
                     Problem (existence/smoothness) in the paper.

Run: python physical_law_verification_en.py
or call individual functions separately.
"""

from mpmath import mp, mpf, exp, quad, inf, gamma, pi, sqrt
import numpy as np

mp.dps = 30  # 30 decimal digits of precision


# ============================================================
# Theorem T1. Time Integral of the Dissipative Semigroup and Delta^-1
#   Integral_0^inf e^{-2n^2 t} dt = 1/(2n^2) = (Delta^-1)_nn
# ============================================================

def T1_dissipative_semigroup_integral():
    """
    NOTE: this function does not prove T1 -- the identity
    Integral_0^inf e^{-at} dt = 1/a (a>0) is already an elementary analytic
    fact. What this function does is confirm that fact numerically for
    n=1..10 at 30-digit precision, i.e. it is an analytic-identity +
    numerical-verification check, not a computational proof of the theorem.
    """
    print("=== T1 (analytic identity + numerical verification): ===")
    print("    Integral_0^inf e^{-2n^2 t} dt vs 1/(2n^2)")
    print(f"{'n':>3} {'analytic 1/(2n^2)':>22} {'numeric integral':>22} {'abs error':>14}")
    rows = []
    for n in range(1, 11):
        n_mp = mpf(n)
        analytic = 1 / (2 * n_mp**2)
        numeric = quad(lambda t: exp(-2 * n_mp**2 * t), [0, inf])
        err = abs(analytic - numeric)
        rows.append((n, analytic, numeric, err))
        print(f"{n:>3} {str(analytic):>22} {str(numeric):>22} {str(err):>14}")
    max_err = max(r[3] for r in rows)
    print(f"\n  Max abs error over n=1..10: {max_err}")
    assert max_err < mpf('1e-20')
    print("  Confirmed: analytic and numeric integration agree to >20 digits.\n")
    return rows


# ============================================================
# Theorem T2. Time Integral of the d-Dimensional Heat Kernel
#   G(r) = Integral_0^inf (4*pi*t)^{-d/2} e^{-r^2/4t} dt
#        = Gamma(d/2-1) / (4*pi^{d/2}) * r^{2-d}
#   At d=3: G(r) = 1/(4*pi*r)
# ============================================================

def T2_heat_kernel_greens_function(d=3):
    """
    NOTE: this function does not prove T2 -- it confirms numerically, for
    the case actually used in the paper (d=3), that the analytic Green's
    function 1/(4*pi*r) matches the time-integrated heat kernel. This is
    an analytic-identity + numerical-verification check, not a
    computational proof.

    The integral only converges for d>2 (at d=2, Gamma(d/2-1)=Gamma(0)
    diverges, and the heat-kernel time integral itself is logarithmically
    divergent). d is left as a parameter for exploration, but any d<=2
    is asserted against rather than silently mishandled.
    """
    assert d > 2, "T2's time integral only converges for d>2 (diverges at d=2, ill-defined below)."
    print(f"=== T2 (analytic identity + numerical verification): Green's function, d={d} ===")
    print(f"{'r':>6} {'analytic G(r)':>22} {'numeric integral':>22} {'abs error':>14}")
    rows = []
    for r_val in [0.5, 1.0, 2.0, 3.0]:
        r = mpf(r_val)
        if d == 3:
            analytic = 1 / (4 * pi * r)
        else:
            analytic = gamma(mpf(d)/2 - 1) / (4 * pi**(mpf(d)/2)) * r**(2 - d)
        numeric = quad(lambda t: (4 * pi * t) ** (-mpf(d) / 2) * exp(-r**2 / (4 * t)), [0, inf])
        err = abs(analytic - numeric)
        rows.append((r_val, analytic, numeric, err))
        print(f"{r_val:>6} {str(analytic):>22} {str(numeric):>22} {str(err):>14}")
    max_err = max(r[3] for r in rows)
    print(f"\n  Max abs error over r in [0.5,1.0,2.0,3.0]: {max_err}")
    assert max_err < mpf('1e-8')
    print("  Confirmed: analytic Green's function 1/(4*pi*r) matches numeric integration within 1e-8.\n")
    return rows


# ============================================================
# Section 6 addendum. Energy-Neutrality of the Triple-Coupling Tensor
#   (INCIDENTAL EXPLORATION -- standard energy method, not a Delta-
#   structure result. See paper Section 6 addendum for full discussion.)
#
#   u(x,t) = sum_k c_k(t) e^{ikx}  (eigenbasis of Delta = -d^2/dx^2)
#   Viscous Burgers (1D analogue of NS advection):
#     dc_k/dt = -nu*k^2*c_k  (linear, from Delta itself)
#               - (i*k/2) * sum_{m+n=k} c_m*c_n   (nonlinear, triple-coupling)
#
#   Claim: the nonlinear (triple-coupling) term contributes exactly ZERO
#   to d/dt sum_k |c_k|^2 (energy). Only the linear/viscous term dissipates.
#   This mirrors the physical-space identity Integral[u^2 u_x]dx = 0
#   (periodic boundary, total derivative).
# ============================================================

def triple_coupling_tensor_energy_neutrality(N=40, nu=0.1, seed=0):
    print("=== Sec.6 addendum: energy-neutrality of the triple-coupling tensor ===")
    print("(Incidental exploration via standard energy method; not a Delta-derived result.)")
    rng = np.random.default_rng(seed)
    ks = np.arange(-N, N + 1)
    idx = {k: i for i, k in enumerate(ks)}

    c = (rng.standard_normal(len(ks)) + 1j * rng.standard_normal(len(ks))) * np.exp(-0.05 * ks**2)
    # enforce reality of u(x,t): c_{-k} = conj(c_k)
    for k in ks:
        if k < 0:
            c[idx[k]] = np.conj(c[idx[-k]])
    c[idx[0]] = c[idx[0]].real

    def dcdt_nonlinear(c):
        # dc_k/dt (nonlinear part) = -(i k /2) * sum_{m+n=k} c_m c_n
        out = np.zeros_like(c)
        for ki, k in enumerate(ks):
            s = 0.0 + 0.0j
            for mi, m in enumerate(ks):
                n = k - m
                if n in idx:
                    s += c[mi] * c[idx[n]]
            out[ki] = -(1j * k / 2.0) * s
        return out

    def dcdt_linear(c):
        return -nu * (ks**2) * c

    nl = dcdt_nonlinear(c)
    lin = dcdt_linear(c)

    dE_nonlinear = np.sum(np.real(np.conj(c) * nl))
    dE_linear = np.sum(np.real(np.conj(c) * lin))

    print(f"  Nonlinear (triple-coupling) contribution to dE/dt: {dE_nonlinear:.3e}  (claim: exactly 0)")
    print(f"  Linear (viscous) contribution to dE/dt:            {dE_linear:.6f}  (claim: <= 0)")
    print(f"  Total dE/dt:                                       {dE_nonlinear + dE_linear:.6f}")
    assert abs(dE_nonlinear) < 1e-8
    print("  Confirmed: nonlinear energy contribution is zero to machine precision.\n")
    return dE_nonlinear, dE_linear


# ============================================================
# Section 3.1. Magnitude/Phase Separation of V_mn(t)
#   V_mn(t) = c_m c_n* e^{lambda_m t} e^{lambda_n* t}
#           = c_m c_n* e^{-(m^2+n^2)t} * e^{i(m^2-n^2)t}
#   Claim: this factors exactly into a real-axis envelope
#   (magnitude, e^{-(m^2+n^2)t}) and an imaginary-axis phase
#   (e^{i(m^2-n^2)t}), with the diagonal (m=n) collapsing to a
#   pure real-axis quantity (phase term = 1).
# ============================================================

def section3_1_Vmn_magnitude_phase_separation(pairs=None, t_vals=None, seed=1):
    print("=== Sec.3.1: magnitude/phase separation of V_mn(t) ===")
    if pairs is None:
        pairs = [(1, 1), (2, 2), (1, 2), (2, 3), (3, 5), (4, 4)]
    if t_vals is None:
        t_vals = [0.1, 0.5, 1.0]

    rng = np.random.default_rng(seed)
    print(f"{'(m,n)':>7} {'t':>5} {'|Vmn| computed':>16} {'envelope pred.':>16} {'phase computed':>16} {'phase pred.':>16} {'max err':>10}")
    max_err = 0.0
    for (m, n) in pairs:
        cm = complex(rng.standard_normal(), rng.standard_normal())
        cn = complex(rng.standard_normal(), rng.standard_normal())
        for t in t_vals:
            lam_m = -(m**2) + 1j * (m**2)     # lambda_n = -n^2 + i*omega_n, omega_n = n^2
            lam_n_conj = -(n**2) - 1j * (n**2)
            Vmn = cm * np.conj(cn) * np.exp(lam_m * t) * np.exp(lam_n_conj * t)

            envelope_pred = abs(cm * np.conj(cn)) * np.exp(-(m**2 + n**2) * t)
            phase_pred = np.exp(1j * (m**2 - n**2) * t)

            computed_envelope = abs(Vmn)
            computed_phase = Vmn / (cm * np.conj(cn) * envelope_pred / abs(cm*np.conj(cn))) if False else None
            # recompute phase directly: Vmn / (|cmcn*| * envelope) should equal phase_pred * (cmcn*/|cmcn*|)
            unit_coeff = (cm * np.conj(cn)) / abs(cm * np.conj(cn))
            computed_phase_factor = Vmn / (abs(cm * np.conj(cn)) * np.exp(-(m**2+n**2)*t) * unit_coeff)

            err_envelope = abs(computed_envelope - envelope_pred)
            err_phase = abs(computed_phase_factor - phase_pred)
            err = max(err_envelope, err_phase)
            max_err = max(max_err, err)

            if m == n:
                # diagonal: phase must collapse to 1 (Generation, pure real axis)
                assert abs(phase_pred - 1.0) < 1e-12, "diagonal phase should be exactly 1"

            phase_str = f"{complex(computed_phase_factor).real:.4f}{complex(computed_phase_factor).imag:+.4f}j"
            phase_pred_str = f"{complex(phase_pred).real:.4f}{complex(phase_pred).imag:+.4f}j"
            print(f"{str((m,n)):>7} {t:>5} {computed_envelope:>16.10f} {envelope_pred:>16.10f} "
                  f"{phase_str:>16} {phase_pred_str:>16} {err:>10.2e}")

    print(f"\n  Max error across all (m,n,t): {max_err:.2e}")
    assert max_err < 1e-8
    print("  Confirmed: V_mn(t) factors exactly into real-axis envelope x imaginary-axis phase;")
    print("  diagonal (m=n) collapses to pure real axis (phase=1), as claimed in Sec.3.2.\n")


# ============================================================
# Section 10. Relaxation-Decoherence Inequality
#   Gamma_relax(n) = 2n^2   (diagonal decay rate)
#   Gamma_decoh(m,n) = m^2+n^2   (off-diagonal decay rate, m != n)
#   Claim (10.1): Gamma_decoh(m,n) > Gamma_relax(min(m,n)) for all m != n.
#   Algebraic reason: with p=max(m,n), q=min(m,n), p>q>=1:
#     (p^2+q^2) - 2q^2 = p^2-q^2 = (p-q)(p+q) >= 1*(2q+1) = 2q+1 > 0.
# ============================================================

def section10_relaxation_decoherence_inequality(N=50):
    print("=== Sec.10: relaxation-decoherence inequality (10.1) ===")
    violations = 0
    checked = 0
    min_margin = None
    for m in range(1, N + 1):
        for n in range(1, N + 1):
            if m == n:
                continue
            checked += 1
            gamma_decoh = m**2 + n**2
            gamma_relax = 2 * (min(m, n) ** 2)
            margin = gamma_decoh - gamma_relax
            if min_margin is None or margin < min_margin:
                min_margin = margin
            if margin <= 0:
                violations += 1

    print(f"  Pairs checked (m,n in 1..{N}, m!=n): {checked}")
    print(f"  Violations of Gamma_decoh > Gamma_relax: {violations}")
    print(f"  Minimum margin observed: {min_margin} (predicted lower bound: 2*min(m,n)+1)")
    assert violations == 0
    print("  Confirmed: the inequality holds for all checked pairs.\n")


# ============================================================
# Appendix K / T7. Many-Body Gravity as Green's Function Superposition
#   Claim: because Delta is LINEAR, Delta[sum_i q_i G(|r-r_i|)] =
#   sum_i q_i delta(r-r_i). We verify this directly and robustly by
#   applying a discrete 3D Laplacian stencil to the analytic superposition
#   phi(r) = sum_i q_i/(4*pi*|r-r_i|) at points AWAY from all sources,
#   where the claim reduces to Delta phi = 0 (Laplace's equation holds
#   away from sources; this is the clean, singularity-free part of the
#   claim to check numerically -- the delta-function part at each source
#   is not something a finite grid can verify directly).
#
#   NOTE: an earlier version of this check attempted a full Poisson solve
#   on a truncated finite-difference grid; that produced large errors
#   because a truncated domain does not have the free-space (r->infinity)
#   boundary condition the analytic Green's function assumes. This
#   version avoids that issue entirely by testing linearity directly.
# ============================================================

def T7_many_body_gravity_superposition(N_masses=3, seed=2):
    print("=== Appendix K / T7: many-body Green's function superposition ===")
    rng = np.random.default_rng(seed)

    src_positions = [rng.uniform(-0.3, 0.3, size=3) for _ in range(N_masses)]
    charges = [rng.uniform(0.5, 2.0) for _ in range(N_masses)]

    def phi_superposition(r):
        return sum(q / (4*np.pi*np.linalg.norm(r - s)) for q, s in zip(charges, src_positions))

    def discrete_laplacian(f, r, h):
        lap = 0.0
        for axis in range(3):
            dr = np.zeros(3); dr[axis] = h
            lap += (f(r+dr) - 2*f(r) + f(r-dr)) / h**2
        return lap

    # Step 0: convergence check at one fixed test point. The finite-difference
    # Laplacian has O(h^2) truncation error alongside O(eps/h^2) floating-point
    # round-off error; the two trade off, giving a U-shaped error curve with a
    # minimum near h~1e-4 for double precision. We confirm this before trusting
    # any single value of |Delta(phi)| as evidence.
    pt0 = None
    h_scan = [1e-1, 1e-2, 1e-3, 1e-4, 1e-5, 1e-6]
    print("  Convergence scan (confirms O(h^2) truncation error, not a physical discrepancy):")
    print(f"  {'h':>10} {'|Delta(phi)|':>16} {'ratio to previous':>18}")
    prev = None
    for _ in range(1):
        pt0 = rng.uniform(-1.0, 1.0, size=3)
        while any(np.linalg.norm(pt0 - s) < 0.2 for s in src_positions):
            pt0 = rng.uniform(-1.0, 1.0, size=3)
    for h in h_scan:
        val = abs(discrete_laplacian(phi_superposition, pt0, h))
        ratio = (prev/val) if prev else None
        print(f"  {h:>10.0e} {val:>16.6e} {('%.2f'%ratio if ratio else '-'):>18}")
        prev = val
    print("  (error shrinks ~100x per 10x decrease in h down to h~1e-4, confirming O(h^2)")
    print("   truncation error; below that, floating-point round-off dominates and error")
    print("   grows again -- the classic double-precision finite-difference U-curve.)\n")

    h_optimal = 1e-4  # empirically near the minimum of the truncation/round-off trade-off
    print(f"{'test point':>26} {'Delta(phi) numeric':>20} {'expected (away from sources)':>30}")
    max_lap = 0.0
    for _ in range(5):
        pt = rng.uniform(-1.0, 1.0, size=3)
        # ensure test point is comfortably away from every source (avoid singularity)
        if any(np.linalg.norm(pt - s) < 0.2 for s in src_positions):
            continue
        lap_val = discrete_laplacian(phi_superposition, pt, h_optimal)
        max_lap = max(max_lap, abs(lap_val))
        print(f"{str(np.round(pt,3)):>26} {lap_val:>20.3e} {'0 (Laplace eq.)':>30}")

    print(f"\n  Max |Delta(phi)| across test points (h={h_optimal:.0e}): {max_lap:.2e}")
    assert max_lap < 1e-5
    print("  Confirmed: the linear superposition sum_i q_i G(|r-r_i|) satisfies Laplace's equation")
    print("  (Delta phi ~ 0) away from all sources, consistent with Delta's linearity acting")
    print("  independently on each source's Green's function.\n")


if __name__ == "__main__":
    T1_dissipative_semigroup_integral()
    T2_heat_kernel_greens_function(d=3)
    triple_coupling_tensor_energy_neutrality()
    section3_1_Vmn_magnitude_phase_separation()
    section10_relaxation_decoherence_inequality()
    T7_many_body_gravity_superposition()
